# Generated by Django 5.2.17 on 2026-10-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Set for staff accounts created by another staff member; cleared after first-login password change.'),
        ),
    ]
