# Generated by Django 5.2.17 on 2026-10-05 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_must_change_password'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0007_grade_schoolbranch_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='schools.schoolbranch'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'branch'], name='idx_user_role_branch'),
        ),
    ]
