# Generated by Django 5.2.18 on 2026-10-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_ensure_panel_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_verified",
            field=models.BooleanField(
                default=False,
                help_text="True once the phone number has been confirmed by OTP. Only verified numbers are used to link a parent to children on the school roster.",
            ),
        ),
    ]
