# Generated by Django 5.2.17 on 2026-10-02 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('orders', '0002_order_parent_order_idx_order_parent_created'),
        ('schools', '0002_student_city_student_idx_student_city_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='schools.city'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='schools.city'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='schools.school'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='schools.city'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='schools.school'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['city', 'category', 'active'], name='idx_prod_city_cat_active'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['school', 'active'], name='idx_variant_school_active'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['city', 'active'], name='idx_variant_city_active'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['city', 'created_at'], name='idx_stockmov_city_created'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['school', 'created_at'], name='idx_stockmov_school_created'),
        ),
    ]
