# Generated by Django 5.2.17 on 2026-10-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_city_productvariant_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product_id', 'size']},
        ),
    ]
