# Generated by Django 5.2.17 on 2026-10-03 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_productvariant_options'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock_quantity',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
