# Generated by Django 5.2.17 on 2026-10-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_productvariant_low_stock_threshold_and_more'),
        ('schools', '0005_school_home_delivery_enabled_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'id'], name='idx_product_active_id'),
        ),
    ]
