# Generated by Django 5.2.17 on 2026-10-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_idx_product_active_id'),
        ('schools', '0005_school_home_delivery_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='class_from',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Lowest class this item applies to (school items only).', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='class_to',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Highest class this item applies to (school items only).', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('UNISEX', 'Unisex'), ('MALE', 'Boys'), ('FEMALE', 'Girls')], default='UNISEX', help_text='Restrict to boys/girls, or UNISEX for everyone.', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('class_from__isnull', True), ('class_to__isnull', True), ('class_to__gte', models.F('class_from')), _connector='OR'), name='product_class_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('school__isnull', False), models.Q(('class_from__isnull', True), ('class_to__isnull', True)), _connector='OR'), name='product_class_range_needs_school'),
        ),
    ]
