# Generated by Django 5.2.17 on 2026-10-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_class_from_product_class_to_product_gender_and_more'),
        ('schools', '0007_grade_schoolbranch_alter_student_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='product_class_range_valid',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='product_class_range_needs_school',
        ),
        migrations.AddField(
            model_name='product',
            name='grades',
            field=models.ManyToManyField(blank=True, db_table='catalog_product_grades', help_text='Grades this product is designated for.', related_name='products', to='schools.grade'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('SOCKS', 'Socks'), ('BELT', 'Belt'), ('TIE', 'Tie')], help_text='Subtype for Uniform Accessories (Socks, Belt, Tie).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='class_from',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Lowest class this item applies to (legacy / school items only).', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='class_to',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Highest class this item applies to (legacy / school items only).', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('BOTH', 'Both')], default='BOTH', help_text='Restrict to Male/Female, or Both for unisex items.', max_length=16),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['school', 'category', 'gender', 'active'], name='idx_prod_sch_cat_gen_act'),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX IF NOT EXISTS idx_prod_grade_grade_prod "
                "ON catalog_product_grades (grade_id, product_id);"
            ),
            reverse_sql=(
                "DROP INDEX IF EXISTS idx_prod_grade_grade_prod;"
            ),
        ),
    ]
