# Generated by Django 5.2.17 on 2026-10-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_gender_and_needs_review'),
        ('schools', '0010_student_idx_stud_sch_grd_gen_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['school', 'class_from', 'gender'], name='idx_prod_sch_class_gen'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['school', 'class_from', 'class_to', 'gender'], name='idx_prod_sch_cls_rng_gen'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['school', 'gender'], name='idx_prod_school_gender'),
        ),
    ]
