# Generated by Django 5.2.17 on 2026-10-02 10:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=40, unique=True)),
                ('placed_by_role', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=24)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=24)),
                ('razorpay_order_id', models.CharField(blank=True, default='', max_length=80)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=80)),
                ('razorpay_signature', models.CharField(blank=True, default='', max_length=200)),
                ('delivery_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='schools.city')),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placed_orders', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='schools.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customisation_data', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.category')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], max_length=24)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='orders.order')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['school', 'created_at'], name='idx_order_school_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['city', 'created_at'], name='idx_order_city_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['student', 'created_at'], name='idx_order_student_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='idx_order_status_created'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='idx_orderitem_order'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['variant'], name='idx_orderitem_variant'),
        ),
        migrations.AddIndex(
            model_name='orderstatusevent',
            index=models.Index(fields=['order', 'timestamp'], name='idx_orderevent_order_ts'),
        ),
    ]
