# Generated by Django 5.2.17 on 2026-10-03 06:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def backfill_payer_and_parent(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    alias = schema_editor.connection.alias
    Order.objects.using(alias).filter(payer__isnull=True).update(payer=F("placed_by"))

    Student = apps.get_model("schools", "Student")
    quote = schema_editor.quote_name
    order_table = quote(Order._meta.db_table)
    student_table = quote(Student._meta.db_table)
    order_parent = quote(Order._meta.get_field("parent").column)
    order_student = quote(Order._meta.get_field("student").column)
    student_parent = quote(Student._meta.get_field("parent").column)
    student_id = quote(Student._meta.pk.column)
    schema_editor.execute(
        f"UPDATE {order_table} AS order_row "
        f"SET {order_parent} = student.{student_parent} "
        f"FROM {student_table} AS student "
        f"WHERE order_row.{order_student} = student.{student_id} "
        f"AND order_row.{order_parent} IS NULL "
        f"AND student.{student_parent} IS NOT NULL"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_checkout'),
        ('schools', '0005_school_home_delivery_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_type',
            field=models.CharField(choices=[('HOME_DELIVERY', 'Home delivery'), ('SCHOOL_PICKUP', 'School pickup')], default='HOME_DELIVERY', max_length=24),
        ),
        migrations.AddField(
            model_name='order',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_payer_and_parent, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(default=uuid.uuid4, max_length=128, unique=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['placed_by', 'created_at'], name='idx_order_placer_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payer', 'created_at'], name='idx_order_payer_created'),
        ),
    ]
