# Generated by Django 5.2.17 on 2026-10-05 03:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_fulfillment_type_order_payer_and_more'),
        ('schools', '0005_school_home_delivery_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='student_class',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['school', 'created_at', 'id'], name='idx_order_school_created_id'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['school', 'student_class', 'created_at', 'id'], name='idx_order_sch_cls_created_id'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['student', 'created_at', 'id'], name='idx_order_student_created_id'),
        ),
        # Backfill the denormalised class with ONE set-based UPDATE, never row by row.
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                schema_editor.execute(
                    """
                    UPDATE orders_order AS o
                       SET student_class = s."class"
                      FROM schools_student AS s
                     WHERE s.id = o.student_id
                       AND o.student_class <> s."class";
                    """
                )
                if schema_editor.connection.vendor == "postgresql"
                else None
            ),
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]
