# Generated by Django 5.2.17 on 2026-10-05 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_student_class_and_more'),
        ('schools', '0007_grade_schoolbranch_alter_student_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='schools.schoolbranch'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'created_at'], name='idx_order_branch_created'),
        ),
    ]
