# Generated by Django 5.2.17 on 2026-10-02 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='schools.city'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['city', 'school'], name='idx_student_city_school'),
        ),
    ]
