# Generated by Django 5.2.17 on 2026-10-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_student_city_student_idx_student_city_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['school_id', 'class_name', 'section', 'name']},
        ),
    ]
