# Generated by Django 5.2.17 on 2026-10-03 06:02

from django.db import migrations, models


def synchronize_student_cities(apps, schema_editor):
    Student = apps.get_model("schools", "Student")
    School = apps.get_model("schools", "School")
    quote = schema_editor.quote_name
    student_table = quote(Student._meta.db_table)
    school_table = quote(School._meta.db_table)
    student_city = quote(Student._meta.get_field("city").column)
    student_school = quote(Student._meta.get_field("school").column)
    school_city = quote(School._meta.get_field("city").column)
    school_id = quote(School._meta.pk.column)
    schema_editor.execute(
        f"UPDATE {student_table} AS student "
        f"SET {student_city} = school.{school_city} "
        f"FROM {school_table} AS school "
        f"WHERE student.{student_school} = school.{school_id} "
        f"AND student.{student_city} IS DISTINCT FROM school.{school_city}"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_student_import_and_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='home_delivery_enabled',
            field=models.BooleanField(default=True, help_text='Whether parents may choose home delivery at checkout.'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_pickup_enabled',
            field=models.BooleanField(default=True, help_text='Whether parents may choose pickup at this school at checkout.'),
        ),
        migrations.RunPython(synchronize_student_cities, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.CheckConstraint(condition=models.Q(('home_delivery_enabled', True), ('school_pickup_enabled', True), _connector='OR'), name='school_has_fulfillment_option'),
        ),
    ]
