# Generated by Django 5.2.17 on 2026-10-05 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_home_delivery_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'class_name', 'section', 'name', 'id'], name='idx_student_school_roster'),
        ),
    ]
