# Generated by Django 5.2.17 on 2026-10-05 08:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_student_idx_student_school_roster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, unique=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'School Branches',
                'ordering': ['school', 'city'],
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['school_id', 'grade__sort_order', 'section', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='idx_student_school_cls_sec',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='idx_student_school_roster',
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='schools.city'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, db_column='class', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=16),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='schools.grade'),
        ),
        migrations.AddField(
            model_name='schoolbranch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_branches', to='schools.city'),
        ),
        migrations.AddField(
            model_name='schoolbranch',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='schools.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schools.schoolbranch'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'grade', 'section'], name='idx_student_school_grd_sec'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['branch'], name='idx_student_branch'),
        ),
        migrations.AddIndex(
            model_name='schoolbranch',
            index=models.Index(fields=['city'], name='idx_schoolbranch_city'),
        ),
        migrations.AddConstraint(
            model_name='schoolbranch',
            constraint=models.UniqueConstraint(fields=('school', 'city'), name='uniq_schoolbranch_school_city'),
        ),
    ]
