# Generated by Django 5.2.17 on 2026-10-06 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_update_grade_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'grade', 'gender'], name='idx_stud_sch_grd_gen'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'class_name', 'gender'], name='idx_stud_sch_cls_gen'),
        ),
    ]
