# Generated by Django 5.2.18 on 2026-10-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0010_student_idx_stud_sch_grd_gen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="roster_phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Parent's mobile number from the school's records (10 digits). A parent who verifies this number by OTP is linked automatically.",
                max_length=10,
            ),
        ),
    ]
