# Generated by Django 5.2.17 on 2026-10-02 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('catalog', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalessummary',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='dailysalessummary',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='schools.city'),
        ),
        migrations.AddField(
            model_name='dailysalessummary',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='schools.school'),
        ),
        migrations.AddIndex(
            model_name='dailysalessummary',
            index=models.Index(fields=['date', 'city'], name='idx_dailysales_date_city'),
        ),
        migrations.AddConstraint(
            model_name='dailysalessummary',
            constraint=models.UniqueConstraint(fields=('date', 'school', 'category'), name='uniq_dailysales_date_sch_cat'),
        ),
    ]
