# Generated by Django 5.2.17 on 2026-10-05 03:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('catalog', '0007_product_class_from_product_class_to_product_gender_and_more'),
        ('schools', '0005_school_home_delivery_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchoolTotal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('orders', models.PositiveIntegerField(default=0)),
                ('units', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name_plural': 'Daily School Totals',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='dailysalessummary',
            index=models.Index(fields=['school', 'date'], name='idx_dailysales_school_date'),
        ),
        migrations.AddField(
            model_name='dailyschooltotal',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_totals', to='schools.city'),
        ),
        migrations.AddField(
            model_name='dailyschooltotal',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_totals', to='schools.school'),
        ),
        migrations.AddIndex(
            model_name='dailyschooltotal',
            index=models.Index(fields=['school', 'date'], name='idx_dschooltotal_sch_date'),
        ),
        migrations.AddIndex(
            model_name='dailyschooltotal',
            index=models.Index(fields=['date', 'city'], name='idx_dailyschooltotal_date_city'),
        ),
        migrations.AddConstraint(
            model_name='dailyschooltotal',
            constraint=models.UniqueConstraint(fields=('date', 'school'), name='uniq_dailyschooltotal_date_sch'),
        ),
    ]
