# Generated by Django 5.2.17 on 2026-10-05 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_dailyschooltotal_and_more'),
        ('catalog', '0007_product_class_from_product_class_to_product_gender_and_more'),
        ('schools', '0006_student_idx_student_school_roster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('orders', models.PositiveIntegerField(default=0)),
                ('units', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name_plural': 'Daily Product Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='dailysalessummary',
            name='idx_dailysales_date_city',
        ),
        migrations.RemoveIndex(
            model_name='dailysalessummary',
            name='idx_dailysales_school_date',
        ),
        migrations.RemoveIndex(
            model_name='dailyschooltotal',
            name='idx_dschooltotal_sch_date',
        ),
        migrations.RemoveIndex(
            model_name='dailyschooltotal',
            name='idx_dailyschooltotal_date_city',
        ),
        migrations.AddIndex(
            model_name='dailysalessummary',
            index=models.Index(fields=['date'], include=('orders', 'units', 'revenue', 'cost'), name='idx_ds_cover_date'),
        ),
        migrations.AddIndex(
            model_name='dailysalessummary',
            index=models.Index(fields=['city', 'date'], include=('orders', 'units', 'revenue', 'cost'), name='idx_ds_cover_city_date'),
        ),
        migrations.AddIndex(
            model_name='dailysalessummary',
            index=models.Index(fields=['school', 'date'], include=('orders', 'units', 'revenue', 'cost'), name='idx_ds_cover_school_date'),
        ),
        migrations.AddIndex(
            model_name='dailysalessummary',
            index=models.Index(fields=['category', 'date'], include=('orders', 'units', 'revenue', 'cost'), name='idx_ds_cover_cat_date'),
        ),
        migrations.AddIndex(
            model_name='dailyschooltotal',
            index=models.Index(fields=['date'], include=('orders', 'units', 'revenue', 'cost'), name='idx_dst_cover_date'),
        ),
        migrations.AddIndex(
            model_name='dailyschooltotal',
            index=models.Index(fields=['city', 'date'], include=('orders', 'units', 'revenue', 'cost'), name='idx_dst_cover_city_date'),
        ),
        migrations.AddIndex(
            model_name='dailyschooltotal',
            index=models.Index(fields=['school', 'date'], include=('orders', 'units', 'revenue', 'cost'), name='idx_dst_cover_school_date'),
        ),
        migrations.AddField(
            model_name='dailyproductsummary',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_daily_summaries', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='dailyproductsummary',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_daily_summaries', to='schools.city'),
        ),
        migrations.AddField(
            model_name='dailyproductsummary',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='dailyproductsummary',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_daily_summaries', to='schools.school'),
        ),
        migrations.AddIndex(
            model_name='dailyproductsummary',
            index=models.Index(fields=['date'], include=('product', 'units', 'revenue', 'cost'), name='idx_dp_cover_date'),
        ),
        migrations.AddIndex(
            model_name='dailyproductsummary',
            index=models.Index(fields=['category', 'date'], include=('product', 'units', 'revenue', 'cost'), name='idx_dp_cover_cat_date'),
        ),
        migrations.AddIndex(
            model_name='dailyproductsummary',
            index=models.Index(fields=['city', 'date'], include=('product', 'units', 'revenue', 'cost'), name='idx_dp_cover_city_date'),
        ),
        migrations.AddIndex(
            model_name='dailyproductsummary',
            index=models.Index(fields=['school', 'date'], include=('product', 'units', 'revenue', 'cost'), name='idx_dp_cover_school_date'),
        ),
        migrations.AddConstraint(
            model_name='dailyproductsummary',
            constraint=models.UniqueConstraint(fields=('date', 'product', 'city', 'school'), name='uniq_dailyprod_date_prod_city_sch'),
        ),
    ]
