# Generated by Django 5.2.17 on 2026-10-05 07:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_dailyschooltotal_and_more'),
        ('catalog', '0007_product_class_from_product_class_to_product_gender_and_more'),
        ('schools', '0006_student_idx_student_school_roster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductTotal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('units', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name_plural': 'Daily Product Totals',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='dailysalessummary',
            index=models.Index(fields=['date', 'school', 'category'], name='idx_dailysales_dt_sch_cat'),
        ),
        migrations.AddIndex(
            model_name='dailysalessummary',
            index=models.Index(fields=['date', 'category'], name='idx_dailysales_dt_cat'),
        ),
        migrations.AddField(
            model_name='dailyproducttotal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_product_totals', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='dailyproducttotal',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_product_totals', to='schools.city'),
        ),
        migrations.AddField(
            model_name='dailyproducttotal',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_totals', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='dailyproducttotal',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_product_totals', to='schools.school'),
        ),
        migrations.AddIndex(
            model_name='dailyproducttotal',
            index=models.Index(fields=['date', 'product'], name='idx_dailyprod_date_prod'),
        ),
        migrations.AddIndex(
            model_name='dailyproducttotal',
            index=models.Index(fields=['date', 'category'], name='idx_dailyprod_date_cat'),
        ),
        migrations.AddIndex(
            model_name='dailyproducttotal',
            index=models.Index(fields=['date', 'city'], name='idx_dailyprod_date_city'),
        ),
        migrations.AddIndex(
            model_name='dailyproducttotal',
            index=models.Index(fields=['date', 'school'], name='idx_dailyprod_date_school'),
        ),
        migrations.AddConstraint(
            model_name='dailyproducttotal',
            constraint=models.UniqueConstraint(fields=('date', 'product'), name='uniq_dailyprodtotal_date_prod'),
        ),
    ]
