# Generated by Django 5.2.17 on 2026-10-05 03:41

import django.db.models.deletion
import django.utils.timezone
import panel.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0005_school_home_delivery_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('ORDERS', 'Orders export'), ('STUDENTS', 'Students export')], default='ORDERS', max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Building the file'), ('READY', 'Ready to download'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='QUEUED', max_length=16)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/%Y/%m/')),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, default=panel.models.default_expiry, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='schools.city')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'created_at'], name='idx_exportjob_school_created'), models.Index(fields=['status', 'created_at'], name='idx_exportjob_status_created'), models.Index(fields=['requested_by', 'created_at'], name='idx_exportjob_user_created')],
            },
        ),
    ]
