# Generated by Django 5.2.17 on 2026-10-03 06:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_variant_stock(apps, schema_editor):
    """Move old global/school stock into city balances before dropping variant fields.

    School-specific variants keep their existing quantity in the school's city.
    Legacy generic stock had no city attribution, so it is split evenly between
    existing cities (remainder assigned by city code) to preserve total units.
    """
    db = schema_editor.connection.alias
    City = apps.get_model("schools", "City")
    ProductVariant = apps.get_model("catalog", "ProductVariant")
    LegacyMovement = apps.get_model("catalog", "StockMovement")
    StockBalance = apps.get_model("inventory", "StockBalance")
    StockMovement = apps.get_model("inventory", "StockMovement")

    city_ids = list(
        City.objects.using(db).order_by("code").values_list("id", flat=True)
    )
    balances = []
    variant_city_map = {}
    for variant in (
        ProductVariant.objects.using(db)
        .select_related("product")
        .all()
        .iterator(chunk_size=1000)
    ):
        city_id = variant.city_id or variant.product.city_id
        legacy_quantity = int(variant.stock_quantity)
        threshold = int(variant.low_stock_threshold)
        if legacy_quantity < 0 or threshold < 0:
            raise RuntimeError(
                f"Cannot migrate variant {variant.sku}: stock quantity and low-stock "
                "threshold must be nonnegative. Reconcile the legacy values and retry."
            )
        if city_id is not None:
            allocations = [(city_id, legacy_quantity)]
            variant_city_map[variant.pk] = city_id
        elif city_ids:
            quotient, remainder = divmod(legacy_quantity, len(city_ids))
            allocations = [
                (city_id, quotient + (1 if index < remainder else 0))
                for index, city_id in enumerate(city_ids)
            ]
            variant_city_map[variant.pk] = city_ids[0]
        elif legacy_quantity == 0:
            continue
        else:
            raise RuntimeError(
                "Cannot migrate nonzero variant stock because the database has no cities. "
                "Create the city records and retry the migration."
            )

        for target_city_id, quantity in allocations:
            balances.append(
                StockBalance(
                    id=uuid.uuid4(),
                    city_id=target_city_id,
                    variant_id=variant.pk,
                    stock_quantity=quantity,
                    low_stock_threshold=threshold,
                )
            )

    if balances:
        StockBalance.objects.using(db).bulk_create(balances, batch_size=500)

    movements = []
    for movement in LegacyMovement.objects.using(db).all().iterator(chunk_size=1000):
        city_id = movement.city_id or variant_city_map.get(movement.variant_id)
        if city_id is None and city_ids:
            city_id = city_ids[0]
        if city_id is None:
            raise RuntimeError(
                "Cannot migrate legacy stock movement without a city. "
                "Create the city records and retry the migration."
            )
        movements.append(
            StockMovement(
                id=movement.pk,
                city_id=city_id,
                school_id=movement.school_id,
                variant_id=movement.variant_id,
                quantity_change=movement.quantity_change,
                reason=movement.reason,
                reference_order_id=movement.reference_order_id,
                created_by_id=movement.created_by_id,
                created_at=movement.created_at,
            )
        )
        if len(movements) >= 500:
            StockMovement.objects.using(db).bulk_create(movements, batch_size=500)
            movements = []
    if movements:
        StockMovement.objects.using(db).bulk_create(movements, batch_size=500)


def restore_legacy_variant_stock(apps, schema_editor):
    """Best-effort restore the old shared-variant schema when rolling back."""
    from django.db.models import Max, Sum

    db = schema_editor.connection.alias
    ProductVariant = apps.get_model("catalog", "ProductVariant")
    LegacyMovement = apps.get_model("catalog", "StockMovement")
    StockBalance = apps.get_model("inventory", "StockBalance")
    StockMovement = apps.get_model("inventory", "StockMovement")

    stock_by_variant = {
        row["variant_id"]: (row["quantity"] or 0, row["threshold"] or 10)
        for row in StockBalance.objects.using(db)
        .values("variant_id")
        .annotate(quantity=Sum("stock_quantity"), threshold=Max("low_stock_threshold"))
        .iterator(chunk_size=1000)
    }
    for variant in ProductVariant.objects.using(db).all().iterator(chunk_size=1000):
        variant.stock_quantity, variant.low_stock_threshold = stock_by_variant.get(
            variant.pk, (0, 10)
        )
        variant.save(update_fields=["stock_quantity", "low_stock_threshold"])

    legacy_rows = []
    for movement in StockMovement.objects.using(db).all().iterator(chunk_size=1000):
        legacy_rows.append(
            LegacyMovement(
                id=movement.pk,
                variant_id=movement.variant_id,
                city_id=movement.city_id,
                school_id=movement.school_id,
                quantity_change=movement.quantity_change,
                reason=movement.reason,
                reference_order_id=movement.reference_order_id,
                created_by_id=movement.created_by_id,
                created_at=movement.created_at,
            )
        )
        if len(legacy_rows) >= 500:
            LegacyMovement.objects.using(db).bulk_create(legacy_rows, batch_size=500)
            legacy_rows = []
    if legacy_rows:
        LegacyMovement.objects.using(db).bulk_create(legacy_rows, batch_size=500)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0004_alter_productvariant_options"),
        ("orders", "0004_order_fulfillment_type_order_payer_and_more"),
        ("schools", "0005_school_home_delivery_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("low_stock_threshold", models.PositiveIntegerField(default=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("city", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_balances", to="schools.city")),
                ("variant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_balances", to="catalog.productvariant")),
            ],
            options={
                "ordering": ["city_id", "variant_id"],
                "indexes": [models.Index(fields=["city", "stock_quantity"], name="idx_stockbalance_city_qty")],
                "constraints": [
                    models.UniqueConstraint(fields=("city", "variant"), name="uniq_stockbalance_city_variant"),
                    models.CheckConstraint(condition=models.Q(("stock_quantity__gte", 0)), name="stockbalance_quantity_nonnegative"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity_change", models.IntegerField()),
                ("reason", models.CharField(choices=[("INITIAL_STOCK", "Initial Stock"), ("RESTOCK", "Restock"), ("ORDER_PLACED", "Order Placed"), ("ORDER_CANCELLED", "Order Cancelled"), ("ADJUSTMENT", "Manual Adjustment"), ("DAMAGE", "Damaged / Write-off")], default="ADJUSTMENT", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("city", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_movements", to="schools.city")),
                ("school", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stock_movements", to="schools.school")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stock_movements", to=settings.AUTH_USER_MODEL)),
                ("reference_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stock_movements", to="orders.order")),
                ("variant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stock_movements", to="catalog.productvariant")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["variant", "created_at"], name="idx_stockmov_variant_created"),
                    models.Index(fields=["city", "created_at"], name="idx_stockmov_city_created"),
                    models.Index(fields=["school", "created_at"], name="idx_stockmov_school_created"),
                ],
            },
        ),
        migrations.RunPython(migrate_legacy_variant_stock, restore_legacy_variant_stock),
    ]
