# Generated by Django 5.2.17 on 2026-10-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_productvariant_low_stock_threshold_and_more'),
        ('inventory', '0001_initial'),
        ('schools', '0005_school_home_delivery_enabled_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['city', 'updated_at'], name='idx_stockbalance_city_updated'),
        ),
    ]
