# Generated by Django 5.2.17 on 2026-10-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_class_from_product_class_to_product_gender_and_more'),
        ('inventory', '0002_stockbalance_idx_stockbalance_city_updated'),
        ('schools', '0005_school_home_delivery_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbalance',
            name='is_low_stock',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(stock_quantity__lte=models.F('low_stock_threshold'), then=models.Value(True)), default=models.Value(False), output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('INITIAL_STOCK', 'Initial Stock'), ('RESTOCK', 'Restock'), ('ORDER_PLACED', 'Order Placed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('RETURN', 'Customer Return'), ('ADJUSTMENT', 'Manual Adjustment'), ('DAMAGE', 'Damaged / Write-off')], default='ADJUSTMENT', max_length=50),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(condition=models.Q(('is_low_stock', True)), fields=['city', 'variant'], name='idx_stockbalance_low'),
        ),
    ]
