# Generated by Django 5.2.17 on 2026-10-02 11:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0004_student_import_and_search'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('STUDENT_IMPORT', 'Student import')], default='STUDENT_IMPORT', max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending validation'), ('VALIDATING', 'Validating'), ('PREVIEW_READY', 'Preview ready - awaiting confirmation'), ('IMPORTING', 'Importing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=24)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='imports/%Y/%m/')),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('preview', models.JSONField(blank=True, default=dict)),
                ('valid_rows', models.JSONField(blank=True, default=list)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='schools.city')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='schools.school')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'created_at'], name='idx_importjob_school_created'), models.Index(fields=['city', 'created_at'], name='idx_importjob_city_created'), models.Index(fields=['uploaded_by', 'created_at'], name='idx_importjob_user_created'), models.Index(fields=['status', 'created_at'], name='idx_importjob_status_created')],
            },
        ),
    ]
