# Generated by Django 5.2.17 on 2026-10-05 07:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN_CREATED', 'Login Created'), ('STOCK_CHANGED', 'Stock Changed'), ('ORDER_STATUS_CHANGED', 'Order Status Changed'), ('PRICE_CHANGED', 'Price Changed')], max_length=40)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.CharField(max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='idx_audit_action_created'), models.Index(fields=['actor', 'created_at'], name='idx_audit_actor_created'), models.Index(fields=['target_type', 'target_id'], name='idx_audit_target')],
            },
        ),
    ]
